### ISSUE TITLE
streamlit app error

### ISSUE THREAD

**Issue by kklmj** [Tylerbryy/Audify#1]
hi there, I came across this app of yours and it appears to be a great app I could use to convert several ebooks I've been wanting to read. Unfortunately, I'm getting an error message that says to contact support. It'd be great to get some sort of support or perhaps another way to convert the files to audiobooks. thanks

Jake

**Comment by tylergibbs1** [comment]
Hi, this repo isn't maintained anymore check out my recent repo with a better TTS model https://github.com/Tylerbryy/voicecloning-python

**Comment by kklmj** [comment]
Awesome! Thank you!

On 27 Jan 2024, at 18:16, tylerbry ***@***.***> wrote:

﻿

Hi, this repo isn't maintained anymore check out my recent repo with a better TTS model https://github.com/Tylerbryy/voicecloning-python
